package bgc.services.bealert.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-04T14:13:14.082+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:v1.bealert.services.bgc", name = "BeAlertPortType")
@XmlSeeAlso({bgc.objects.vss.checkservice.v1.ObjectFactory.class, bgc.objects.vss.context.v4.ObjectFactory.class, bgc.objects.vss.functionalerror.v1.ObjectFactory.class, bgc.objects.vss.technicalerror.v1.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BeAlertPortType {

    @WebMethod(operationName = "GetGis", action = "GetGis")
    @WebResult(name = "ResponseDataGetGisDataDetails", targetNamespace = "urn:v1.bealert.services.bgc", partName = "GetGisResponseMessagePart")
    public ResponseDataGetGisDataType getGis(
        @WebParam(partName = "GetGisRequestMessagePart", name = "RequestDataGetGisData", targetNamespace = "urn:v1.bealert.services.bgc")
        RequestDataGetGisDataType getGisRequestMessagePart,
        @WebParam(partName = "Context", name = "Context", targetNamespace = "urn:v4.context.vss.objects.bgc", header = true)
        bgc.objects.vss.context.v4.Context context
    ) throws FunctionalFaultMessage, TechnicalFaultMessage;

    @WebMethod(operationName = "CheckService", action = "CheckService")
    @WebResult(name = "ResponseDataCheckService", targetNamespace = "urn:v1.bealert.services.bgc", partName = "CheckServiceResponseMessagePart")
    public bgc.objects.vss.checkservice.v1.ResponseDataCheckServiceType checkService(
        @WebParam(partName = "CheckServiceRequestMessagePart", name = "RequestDataCheckService", targetNamespace = "urn:v1.bealert.services.bgc")
        bgc.objects.vss.checkservice.v1.RequestDataCheckServiceType checkServiceRequestMessagePart,
        @WebParam(partName = "Context", name = "Context", targetNamespace = "urn:v4.context.vss.objects.bgc", header = true)
        bgc.objects.vss.context.v4.Context context
    ) throws FunctionalFaultMessage, TechnicalFaultMessage;

    @WebMethod(operationName = "GetRlts", action = "GetRlts")
    @WebResult(name = "ResponseDataGetRltsDataDetails", targetNamespace = "urn:v1.bealert.services.bgc", partName = "GetRltsResponseMessagePart")
    public ResponseDataGetRltsDataType getRlts(
        @WebParam(partName = "GetRltsRequestMessagePart", name = "RequestDataGetRltsData", targetNamespace = "urn:v1.bealert.services.bgc")
        RequestDataGetRltsDataType getRltsRequestMessagePart,
        @WebParam(partName = "Context", name = "Context", targetNamespace = "urn:v4.context.vss.objects.bgc", header = true)
        bgc.objects.vss.context.v4.Context context
    ) throws FunctionalFaultMessage, TechnicalFaultMessage;
}
