package bgc.services.bealert.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-04T14:13:14.100+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "BeAlert-1.1-Service", 
                  wsdlLocation = "file:/C:/Users/id832037/Documents/PMT%20-%20dev%20work/workspace_keppler/RealTimeLocationParent/RealTimeLocationRESTService/src/main/resources/BeAlert-1.1-standard-http_binding.wsdl",
                  targetNamespace = "urn:v1.bealert.services.bgc") 
public class BeAlert11Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:v1.bealert.services.bgc", "BeAlert-1.1-Service");
    public final static QName BeAlert11SOAPPort = new QName("urn:v1.bealert.services.bgc", "BeAlert-1.1-SOAP-Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/id832037/Documents/PMT%20-%20dev%20work/workspace_keppler/RealTimeLocationParent/RealTimeLocationRESTService/src/main/resources/BeAlert-1.1-standard-http_binding.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BeAlert11Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/id832037/Documents/PMT%20-%20dev%20work/workspace_keppler/RealTimeLocationParent/RealTimeLocationRESTService/src/main/resources/BeAlert-1.1-standard-http_binding.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BeAlert11Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BeAlert11Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BeAlert11Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BeAlert11Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BeAlert11Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BeAlert11Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BeAlertPortType
     */
    @WebEndpoint(name = "BeAlert-1.1-SOAP-Port")
    public BeAlertPortType getBeAlert11SOAPPort() {
        return super.getPort(BeAlert11SOAPPort, BeAlertPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BeAlertPortType
     */
    @WebEndpoint(name = "BeAlert-1.1-SOAP-Port")
    public BeAlertPortType getBeAlert11SOAPPort(WebServiceFeature... features) {
        return super.getPort(BeAlert11SOAPPort, BeAlertPortType.class, features);
    }

}
