
package bgc.services.bealert.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-04T14:13:14.067+02:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "TechnicalError", targetNamespace = "urn:v1.technicalerror.vss.objects.bgc")
public class TechnicalFaultMessage extends Exception {
    
    private bgc.objects.vss.technicalerror.v1.TechnicalErrorType technicalError;

    public TechnicalFaultMessage() {
        super();
    }
    
    public TechnicalFaultMessage(String message) {
        super(message);
    }
    
    public TechnicalFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public TechnicalFaultMessage(String message, bgc.objects.vss.technicalerror.v1.TechnicalErrorType technicalError) {
        super(message);
        this.technicalError = technicalError;
    }

    public TechnicalFaultMessage(String message, bgc.objects.vss.technicalerror.v1.TechnicalErrorType technicalError, Throwable cause) {
        super(message, cause);
        this.technicalError = technicalError;
    }

    public bgc.objects.vss.technicalerror.v1.TechnicalErrorType getFaultInfo() {
        return this.technicalError;
    }
}
